name: Auto Build

on: 
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *        
    
jobs:
  run_Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projectPath:
          - D:\Unity Projects\ThunderJackProjectMIS
        unityVersion:
          - 2022.3.4f1

    steps:            
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: ${{ matrix.unityVersion }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Build Unity Project
        run: |
          -quit -batchmode -buildTarget Win64 -projectPath ${{ matrix.projectPath }} -executeMethod AutoBuildManager.AutoBuild

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: ${{ matrix.projectPath }}
