name: Auto Build

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
    
jobs:
  run_Build:
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - StandaloneWindows64 # Build a Windows 64-bit standalone.
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  lfs: true
            - uses: actions/cache@v2
              with:
                  path: Library
                  key: Library-${{ matrix.targetPlatform }}
                  restore-keys: Library-
                  
            - name: Auto Merge
              run: |
                git config --global user.email "test@C.I"
                git config --global user.name "CI"
                git remote update
                git checkout build          
                git pull
                
            - uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}
            - uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: build/${{ matrix.targetPlatform }}

            - name: Create Artifact Link
              id: artifact
              run: echo "::set-output name=link::$(echo ${{ github.run_id }})"

            - name: Send Discord Notification
              uses: sarisia/actions-status-discord@v1
              if: success()
              with:      
                webhook: ${{ secrets.DISCORD_BUILD }}
                nodetail: true
                description: "빌드의 요정의 선물이 도착했습니다."
                username: "빌드의 요정 김영훈"
                color: "#FF0000"
                url: "https://github.com/${{ github.repository }}/actions/runs/${{ steps.artifact.outputs.link }}"
                avatar_url: "https://cdn.discordapp.com/attachments/1147907186400448605/1149615882432168026/6_-removebg-preview.png"
      
            - name: Send Discord fail
              if: failure()
              with:      
                webhook: ${{ secrets.DISCORD_BUILD }}
                nodetail: true
                description: "방해꾼이 빌드를 방해했습니다."
                username: "빌드 방해꾼 김영훈"
                color: "#ff0000"
                avatar_url: "https://cdn.discordapp.com/attachments/1147907186400448605/1149615498431037540/4_-removebg-preview.png"
